"""Context-file tools.

Gives the agent explicit control over which background files it reads.
Instead of auto-injecting every .md file from data/ into every call,
the agent sees a menu of available files and loads only what it needs.

Typical flow:
  1. Agent receives a question.
  2. Agent calls context_list() to see what context files exist.
  3. Agent calls context_load("personal_profile.md") if it needs Xi's profile,
     context_load("goals.md") for goals, context_load("workout_plan.md")
     for a workout-specific file, etc.
  4. Agent uses the loaded content to answer, skipping files that aren't
     relevant — saving tokens and keeping irrelevant context out.

Files are read from the same data/ directory that file_write targets,
so anything the agent writes is immediately discoverable via context_list.
"""
from __future__ import annotations

from pathlib import Path

from .registry import tool

_DATA_DIR = Path(__file__).parent.parent.parent / "data"

# Files that are internal / auto-generated and should not appear in the menu.
_EXCLUDED = {
    "tool_needs.md",   # auto-generated by prompt_log_need
    "health_summary.md",  # large static export, loaded separately by health tools
}


def _available() -> list[str]:
    """Return sorted list of loadable .md files in data/, including subdirectories.

    Paths are returned relative to data/ (e.g. 'goals/dutch.md') so the agent
    can pass them directly to context_load().
    """
    return sorted(
        str(p.relative_to(_DATA_DIR))
        for p in _DATA_DIR.rglob("*.md")
        if p.name not in _EXCLUDED and p.is_file()
    )


@tool(
    description=(
        "List all context files available to load. "
        "Call this first to see what background information exists before "
        "deciding which files are relevant to the current question."
    ),
    parameters={
        "type": "object",
        "properties": {},
        "required": [],
    },
)
def context_list() -> dict:
    """Return available context filenames."""
    files = _available()
    return {
        "files": files,
        "hint": (
            "Call context_load(filename) for any file relevant to the question. "
            "Skip files that aren't needed."
        ),
    }


@tool(
    description=(
        "Load a context file and return its contents. "
        "Use this to read background info about Xi before answering — "
        "e.g. 'personal_profile.md' for personal details, 'goals.md' for goals, "
        "or any agent-specific file. Call context_list first to see what exists."
    ),
    parameters={
        "type": "object",
        "properties": {
            "filename": {
                "type": "string",
                "description": "Filename to load, e.g. 'personal_profile.md'. Must be a file returned by context_list.",
            },
        },
        "required": ["filename"],
    },
)
def context_load(filename: str) -> str:
    """Read and return the contents of a context file from data/."""
    # Prevent path traversal — block explicit traversal sequences.
    # Forward slashes are allowed (e.g. 'goals/dutch.md'); the resolve()+startswith()
    # check below is the real security guarantee.
    if "\\" in filename or ".." in filename:
        raise ValueError(f"Invalid filename {filename!r}.")
    path = (_DATA_DIR / filename).resolve()
    if not str(path).startswith(str(_DATA_DIR.resolve())):
        raise ValueError(f"Path {filename!r} escapes the data directory.")
    if not path.exists():
        available = ", ".join(_available())
        raise FileNotFoundError(
            f"{filename!r} not found. Available files: {available}"
        )
    return path.read_text(encoding="utf-8")
